### ISSUE TITLE
Json versioning

### ISSUE THREAD

**Issue by ghost1372** [googlesamples/android-topeka#105]
hi Do you have a plan for versioning json (Category.json) file?
For the new version of the program, we need to remove the previous version and install the new version, Otherwise, the information will not be updated.

**Comment by keyboardsurfer** [comment]
Hi. Since there are no suggestions or plans on new content I don't see the use for versioning the JSON at this point.
Are you working on a fork with new categories? If so, I'm keen on taking a look.
