### ISSUE TITLE
Not showing points after answer

### ISSUE THREAD

**Issue by hadiyev94** [googlesamples/android-topeka#107]
There is not showing points after answered question.
But calculating points How can I fix it?
Here is a screenshot about...
![screenshot_1509014348](https://user-images.githubusercontent.com/26745842/32048763-41be84b6-ba53-11e7-852c-2b313b6a021b.png)

**Comment by keyboardsurfer** [comment]
Hi, thanks for opening this issue.
Is this an issue within the current implementation in the repository or did you make changes on top?

**Comment by hadiyev94** [comment]
I just make changes on top. but before change there was same problem: displaying points after answer

**Comment by keyboardsurfer** [comment]
After compiling this, I see where you're coming from.
This has not been implemented.
The progress is for the amount of questions answered per category.
