### ISSUE TITLE
Infinite recursion in CategorySelectionActivity.onActivityResult() (StackOverflowError)

### ISSUE THREAD

**Issue by cketti** [googlesamples/android-topeka#109]
The `onActivityResult()` implementation in `CategorySelectionActivity` intends to dispatch the Activity result to the currently displayed Fragment.

https://github.com/googlesamples/android-topeka/blob/6913c585c7d76a289038a8cc94a6312498684e7c/app/src/main/java/com/google/samples/apps/topeka/activity/CategorySelectionActivity.kt#L101-L107

However, the return value of `findFragmentById()` is nullable. And so the `onActivityResult()` call inside the `with` block doesn't refer to the Fragment's `onActivityResult()` method because that would require ensuring `this` is not null. Instead `onActivityResult()` of the Activity is called. This infinite recursion leads to a `StackOverflowError` crashing the app.

**Comment by keyboardsurfer** [comment]
Hi @cketti and thanks for the bug report. And even better, you already fixed it within #110.
😍
