### ISSUE TITLE
Gradle Sync Failed After Updating to Android Studio 3.1

### ISSUE THREAD

**Issue by NamanSharma21** [googlesamples/android-topeka#115]
After updating to android studio version 3.1 i tried to run the application but it failed with the following error-->

Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.1) from [com.android.support:design:26.0.1] AndroidManifest.xml:28:13-35
	is also present at [com.android.support:support-core-utils:26.1.0] AndroidManifest.xml:28:13-35 value=(26.1.0).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.

**Comment by keyboardsurfer** [comment]
Can not reproduce with the current version of Topeka and Android Studio 3.1. Please reconfirm.
