### ISSUE TITLE
compatible version

### ISSUE THREAD

**Issue by guoyoujin** [googlesamples/android-topeka#14]
Whether can be down more compatible version

**Comment by MrThiago** [comment]
How can we run on lower than 21API ?

**Comment by lawloretienne** [comment]
Will there be support for devices on lower API versions than 21?

**Comment by guoyoujin** [comment]
@lawloretienne Yes, we here most still use 16 17 18 19 API

**Comment by keyboardsurfer** [comment]
Currently there is no support for API levels < 21, as you can see in [`build.gradle`](https://github.com/googlesamples/android-topeka/blob/master/app/build.gradle#L25).
We're evaluating ways to make Topeka available for lower API levels.

**Comment by guoyoujin** [comment]
@keyboardsurfer 好的，不能使用v7兼容包去向下兼容吗？

**Comment by MrThiago** [comment]
@keyboardsurfer , While there is no support for < 21 for this project. Is there other Google material Design sample app that support lower API ? Thank you.

**Comment by paundo** [comment]
http://antonioleiva.com/navigation-view/
https://github.com/antoniolg/MaterializeYourApp

**Comment by andyiac** [comment]
I import the project to android studio , and build success, but it can not install success ,and prompt 
"Parse error ,There was a problem parsing the package"

**Comment by keyboardsurfer** [comment]
@andyiac try running it on a device / emulator with API version 21 or greater.

**Comment by ghost1372** [comment]
When we can use pre-lolipop?
I strongly need it.
tnx

**Comment by keyboardsurfer** [comment]
@ghost1372 can you please elaborate that further?

**Comment by ghost1372** [comment]
I want to run this application on Android phones that are lower.(4.4 or 4.3 or 4.2 etc.)
But is currently only available on Android 5 and higher.
Please add this capability.

**Comment by keyboardsurfer** [comment]
I'm just going to [leave this here](https://plus.google.com/+BenjaminWeiss/posts/LKoLuYC7Vs9)...

**Comment by hoseinit** [comment]
I need this feature, too.
I hope to see the compatible version soon.
Thanks to all

**Comment by keyboardsurfer** [comment]
The [backport scenario](https://github.com/googlesamples/android-topeka/releases/tag/13102015) release supports Android versions down to API level 16.
