### ISSUE TITLE
Sometimes, mIcon is scaled so small size in QuizActivity

### ISSUE THREAD

**Issue by Flashgugu** [googlesamples/android-topeka#15]
When I clicked a Category Item(Food & Drink, General Knowlegde, ... etc), QuizActivity represents mIcon to smaller size.

I'm running on Emulator(API21 / x86)

Sorry, That's all..

![2015-06-18 16 25 30](https://cloud.githubusercontent.com/assets/1423080/8226099/8bcb9162-15d6-11e5-94b5-7d0ffa44accf.png)
![2015-06-18 16 25 51](https://cloud.githubusercontent.com/assets/1423080/8226100/8bec401a-15d6-11e5-9988-6ac34f90ac6d.png)

**Comment by keyboardsurfer** [comment]
Can you please provide further info.

**Comment by Flashgugu** [comment]
When I clicked a Category Item(Food & Drink, General Knowlegde, ... etc), QuizActivity represents mIcon to smaller size.

I'm running on Emulator(API21 / x86)

Sorry, That's all..

**Comment by keyboardsurfer** [comment]
With a standard Nexus 5 emulator with 1080 x1920 xxhdpi, API 21 and x86 architecture I can not reproduce the issue. Feel free to re-open if you can provide further info.
