### ISSUE TITLE
image as part of question

### ISSUE THREAD

**Issue by paundo** [googlesamples/android-topeka#22]
Is possible to add image as part of question?

**Comment by keyboardsurfer** [comment]
The current implementation does not allow this.
You would have to introduce a new quiz type for this.
The data source for quizzes can be found within [categories.json](https://github.com/googlesamples/android-topeka/blob/master/app/src/main/res/raw/categories.json).

**Comment by temkris** [comment]
Do you plan on introducing this in the future?

**Comment by keyboardsurfer** [comment]
From my current point of view I do not have plans to do this.
It's possible nonetheless by extending `AbsQuizView` and returning an ImageView within `createQuizContentView`.
