### ISSUE TITLE
<> Problem

### ISSUE THREAD

**Issue by Zgrkaralar** [googlesamples/android-topeka#29]
Hello,

I need help. I imported this project on android studio and after this i try to run but Android Studio showing me now 70 errors

Error:(97, 54) illegal start of type
Error:(241, 50) illegal start of type
Error:(411, 29) <identifier> expected
Error:(411, 31) '{' expected
Error:(411, 46) not a statement
Error:(411, 47) ';' expected
Error:(416, 5) illegal start of expression
Error:(416, 13) illegal start of expression
Error:(416, 42) ';' expected
Error:(416, 60) ';' expected
Error:(416, 69) not a statement
Error:(416, 82) ';' expected
Error:(416, 84) not a statement
Error:(416, 95) ';' expected
Error:(429, 5) illegal start of expression
Error:(429, 47) ';' expected
Error:(429, 57) not a statement
Error:(429, 68) ';' expected
Error:(441, 5) illegal start of expression
Error:(441, 13) illegal start of expression
Error:(441, 30) ';' expected
Error:(441, 63) ';' expected
Error:(441, 64) not a statement
Error:(441, 70) ';' expected
Error:(442, 19) ';' expected
Error:(442, 20) not a statement
Error:(442, 30) ';' expected
Error:(442, 39) not a statement
Error:(442, 52) ';' expected
Error:(452, 5) illegal start of expression
Error:(452, 13) illegal start of expression
Error:(452, 40) ';' expected
Error:(452, 73) ';' expected
Error:(452, 74) not a statement
Error:(452, 80) ';' expected
Error:(453, 19) ';' expected
Error:(453, 20) not a statement
Error:(453, 30) ';' expected
Error:(453, 39) not a statement
Error:(453, 52) ';' expected
Error:(481, 5) illegal start of expression
Error:(481, 13) illegal start of expression
Error:(481, 35) ';' expected
Error:(481, 68) ';' expected
Error:(481, 69) not a statement
Error:(481, 73) ';' expected
Error:(482, 19) ';' expected
Error:(482, 20) not a statement
Error:(482, 30) ';' expected
Error:(482, 39) not a statement
Error:(482, 52) ';' expected
Error:(489, 2) reached end of file while parsing

That  illegal type showing this "<>"

**Comment by keyboardsurfer** [comment]
Looks like you're trying to build with a version of Java which doesn't support the Diamond operator. Make sure you're building Topeka with at least Java 1.7.
