### ISSUE TITLE
Installation on pre-lollipop

### ISSUE THREAD

**Issue by ghost1372** [googlesamples/android-topeka#31]
Hi,
The application can not be installed on Android 5 down
I have Android 4.4 and 4, but the program is not installed
Please solve this problem.

**Comment by keyboardsurfer** [comment]
Duplicate of #14.

**Comment by ghost1372** [comment]
When we can use pre-lolipop?
I strongly need it.
tnx

**Comment by keyboardsurfer** [comment]
Let's keep the communication on the bug mentioned above. Closing this one.

**Comment by keyboardsurfer** [comment]
Fixed with the latest release.
