### ISSUE TITLE
Clicking submit multiple times submits answers before questions could be seen

### ISSUE THREAD

**Issue by pomerantsev** [googlesamples/android-topeka#39]
If you answer a question and then press the submit button two or three times, the app quickly performs the transition multiple times (looks pretty jumpy), several questions get answered (which is definitely not intended), and then sometimes the submit button's icon (either a cross or a checkmark) is rotated and / or skewed.

Like this:
![screenshot_2015-10-28-23-53-54](https://cloud.githubusercontent.com/assets/3888965/10802708/5fdf09a6-7dcf-11e5-983a-6336627ceeed.png)

**Comment by keyboardsurfer** [comment]
Yeah, I've changed the on click behavior for that button to only do that in a debug build (as it's sometimes useful to fast forward through a category).
Will be shipped with the next release.

**Comment by pomerantsev** [comment]
Cool, thanks Ben.
