### ISSUE TITLE
Check all the items is always considered a correct answer due bug and bad test naming

### ISSUE THREAD

**Issue by ardock** [googlesamples/android-topeka#40]
1 [Only my answers are always correct, this minimal change demonstrates it :)](https://github.com/googlesamples/android-topeka/blob/master/app/src/androidTest/java/com/google/samples/apps/topeka/helper/AnswerHelperTest.java#L40)

![fix_test](https://cloud.githubusercontent.com/assets/1142360/10813708/31d768f8-7e21-11e5-93c5-709c9011b0ba.png)

2 [My teachers were stricter correcting my tests :(](https://github.com/googlesamples/android-topeka/blob/master/app/src/main/java/com/google/samples/apps/topeka/helper/AnswerHelper.java#L88)

![fix_code](https://cloud.githubusercontent.com/assets/1142360/10813725/53728fe2-7e21-11e5-9f6e-68589fffa43e.png)

3 [Put a cat on your life](https://www.google.es/search?q=adopt+a+cat&oq=adopt+a+cat) :smile_cat: 

![test_it](https://cloud.githubusercontent.com/assets/1142360/10813730/5ad84f60-7e21-11e5-91e8-b2ac555c9126.png)

**Comment by keyboardsurfer** [comment]
Pull requests are welcome.

**Comment by ardock** [comment]
The naming problem is that `OPTIONS`  are really the `correctAnswersIds`, 
and the `correctAnswers` are the `checkedItems`.

 I would do something like this:

![test](https://cloud.githubusercontent.com/assets/1142360/10816320/46f95ece-7e32-11e5-94c0-fb9c5cbc02d2.png)

![method](https://cloud.githubusercontent.com/assets/1142360/10816314/3cf85f60-7e32-11e5-9948-d6f1a73ab6e8.png)

but I'm still learning it, thanks for the great Material and Espresso sample.
