### ISSUE TITLE
Floating label overlaps username last initial on S2 API 19 (4.4.4)

### ISSUE THREAD

**Issue by ardock** [googlesamples/android-topeka#44]
Floating label for TextInputLayout overlaps last initial on S2 API 4.4.4

![screenshot_2015-11-04-08-31-58](https://cloud.githubusercontent.com/assets/1142360/10933194/f4bdea86-82d6-11e5-97e6-319e3ee1972f.png)

and the hint is too close to the text field divider.

![screenshot_2015-11-04-08-31-46](https://cloud.githubusercontent.com/assets/1142360/10933204/01c62acc-82d7-11e5-89ef-81b6dbc39c78.png)

I don't know the best way to fix it but I solved it deleting the paddinTop and paddingBottom on both TextInputLayouts.

I tested this change on that device and confirmed that nexus5 and nexus7 still look good.
I can not test it on other devices due to either are not supported or the screen size is greater and are not affected.

Optionally I tried to follow the [Material Design Spec](http://www.google.com/design/spec/components/text-fields.html#text-fields-floating-labels) ,like reducing text size to 16sp as recommended, it helped but it didn't solve the issue.

I can pull request the padding deletion but would be better that someone check it on more devices or propose a better solution. I'm not familiar with this new view.

**Comment by piotrek1543** [comment]
Hi @ardock, I noticed that it happens on small screens. The easiest way is to delete - like you said -paddingTop and paddingDown. The best would be making a few layouts depends on phone screen.
@keyboardsurfer could you confirm my words?

**Comment by ardock** [comment]
Hello @piotrek1543 , I think that would be overkill for a height issue, I'm using this by now.

@keyboardsurfer This is only a workaround, don't merge, I think the problem is [this](https://github.com/googlesamples/android-topeka/search?utf8=%E2%9C%93&q=%22%3Fandroid%3Aattr%22):

> android:layout_height="?**android**:attr/actionBarSize"

**Comment by piotrek1543** [comment]
@ardock could you reopen issue, please.
