### ISSUE TITLE
Logout icon instead of action menu with only one item

### ISSUE THREAD

**Issue by piotrek1543** [googlesamples/android-topeka#51]
Hi,

I would like to suggest you to instead of using exisiting action menu with logout item try to implement nice -looking button in this place. I think it might improve a little an user experience of this app.

What do you think guys about this idea?

Cheers

**Comment by keyboardsurfer** [comment]
Logging out is not one of the flows that happens a lot within the app.
This is why it's an action that requires two taps.
I agree, that the menu button should have a different color to match the style of the toolbar.

**Comment by piotrek1543** [comment]
To make my issue description more clear, I really like an idea used at first screen of this app:
<img src="https://raw.githubusercontent.com/kyleduo/SwitchButton/master/preview/demo_131.jpg" border="0" alt="github.com/kyleduo/SwitchButton/" height="400"></a>

Thanks for comment. Now I can close an issue.

**Comment by keyboardsurfer** [comment]
I don't think that a switch in the toolbar is going to make things more clear.
Or is there something I'm missing out in the screenshot?

**Comment by piotrek1543** [comment]
@keyboardsurfer, switch? I'm thinking about a button on the right side of a toolbar like you can see on the first screen with Github or K logo. Clicking on this will automatically log out user. 
Instead of two clicks than would be only one :-)

**Comment by keyboardsurfer** [comment]
Ok. I see the point now.
Logging out will clear the preferences and remove all scores.
Having a user accidentally press that is not the right approach.

I'll change the menu button's color to white nonetheless.

**Comment by piotrek1543** [comment]
@keyboardsurfer, heh... maybe it's time to implement High Score board. Having this feature would fix this problem: click on logout ---> save user name and score :-)

**Comment by keyboardsurfer** [comment]
API level 21+ now has a menu button color that matches the title text color. Released with a0c8b2f1c0b6161f4901ff685443d7e5b1aca1b8.

**Comment by piotrek1543** [comment]
@keyboardsurfer , good to know. Thanks :-)
