### ISSUE TITLE
[Improvement] Uppercase user answer than check with correct one

### ISSUE THREAD

**Issue by piotrek1543** [googlesamples/android-topeka#56]
Hi,

I've already played Topeka game and I noticed that if I answer the question with lowercase letters like "texas" when correct is "Texas" it returns false and no points.

Could you make a small change in code to make every first letter of user answer capital?

Cheers.

**Comment by keyboardsurfer** [comment]
Please relax with closing issues if there's no immediate response.
If you close them before having any response, chances are that there's not going to be one at all.

**Comment by piotrek1543** [comment]
@keyboardsurfer, sorry, my mistake.

**Comment by keyboardsurfer** [comment]
No need to worry, but weekends exist for reasons. One of them is to stop work every now and then. ;-)
