### ISSUE TITLE
Actually this is not an issue,its a request pls help

### ISSUE THREAD

**Issue by Sarun1001** [googlesamples/android-topeka#57]
How can i update questions from a json file using a server

Is it possible to update  "categories.json" in "raw" folder
I am New to programming  hope someone will help
Thank u
(I know this is not the right place to ask.if is is  inappropriate pls remove it) :)

**Comment by keyboardsurfer** [comment]
For simplicity reasons Topeka does not rely on a server. You can create new questions or modify existing ones within the categories.json. But this is not documented or supported at the moment.
