### ISSUE TITLE
Use of enum for Avatar class.

### ISSUE THREAD

**Issue by IgorGanapolsky** [googlesamples/android-topeka#67]
Hello,
I am wondering why you chose to use `enum` type for drawables in Avatar.java.  According to Google's best practices for Android, enums are more memory hungry than TypeDefs at runtime.  So wouldn't it be more prudent to use `@DrawableRes` as described here: http://tools.android.com/tech-docs/support-annotations?

Thanks,
Igor

**Comment by keyboardsurfer** [comment]
The enum is used for type safety in a bigger picture which outweighs the potential performance gain of support annotations.

**Comment by IgorGanapolsky** [comment]
You can easily have type safety with `DrawableRes`, as is demonstrated here: http://androidxref.com/6.0.0_r1/xref/packages/apps/UnifiedEmail/src/com/android/mail/ui/MaterialSearchActionView.java.

**Comment by keyboardsurfer** [comment]
That's true, but would lack the ease of adding some basic accessibility functionality.

**Comment by IgorGanapolsky** [comment]
It bugs me that Google is zealously advocating TypeDefs over Enums, and telling everybody 'avoid Enums at all costs'.  What should us - indie developers - believe?

**Comment by keyboardsurfer** [comment]
The Android Framework team's most recent [fireside chat](https://youtu.be/-VNfWh5UkfY?t=958) has some great insights in that.

**Comment by IgorGanapolsky** [comment]
@keyboardsurfer  @changetip $1.  Thanks for the nice sample!

**Comment by changetip** [comment]
Hi @keyboardsurfer, @IgorGanapolsky sent you a tip worth 2,765 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/925221)**.



**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**
