### ISSUE TITLE
Duplicate class errors when "Enable all test artifacts" enabled. 

### ISSUE THREAD

**Issue by tasomaniac** [googlesamples/android-topeka#68]
In Android Studio 2.0, in experimental Gradle settings, there is an option to enable all test artifacts at the same time. This removes the necessity to change to "Unit Tests" and "Instrumentation Tests" in Build Variants section every time. 

When this is enabled,  the source sets in both `test` and `androidTest` folders are included. And this causes conflicts in class names. Here is the screenshot. 

![image](https://cloud.githubusercontent.com/assets/763339/12088048/9a525d86-b2e0-11e5-85f5-b60cfd718879.png)

**Comment by keyboardsurfer** [comment]
I currently do not see an urge to fix this, as it is part of an experimental setting.
If this issue persists, please file a bug on the [Android bugtracker](https://code.google.com/p/android/issues/entry?template=Tools%20bug%20report).

**Comment by tasomaniac** [comment]
I think this should be fixed on the client side. It is because when this setting is enabled, both folders are added as source folders. I think tools team cannot do anything about it but I will file a bug there. Let's see their response.

**Comment by keyboardsurfer** [comment]
Feel free to link the bug you created here for reference.

**Comment by tasomaniac** [comment]
Here it is: https://code.google.com/p/android/issues/detail?id=198159

**Comment by tasomaniac** [comment]
In Android Studio 2.0 Preview 5 release, they enabled this option by default. It is no longer an experimental feature (except the fact that it is in preview build :smile:)

In the screenshots in the changelog they have Android Topeka as an example but it still causes problem with it.

**Comment by sergiiz** [comment]
Problem still exists in Android Studio 2.0 Beta 6

**Comment by keyboardsurfer** [comment]
Will be fixed with the next Topeka release.
