### ISSUE TITLE
Find a memory leak with TopekaDatabaseHelper

### ISSUE THREAD

**Issue by Mcflag** [googlesamples/android-topeka#70]
I combined this project with LeakCanary,and find a memory leak, here are the details:

* com.google.samples.apps.topeka.activity.CategorySelectionActivity has leaked:
* GC ROOT static com.google.samples.apps.topeka.persistence.TopekaDatabaseHelper.mInstance
* references com.google.samples.apps.topeka.persistence.TopekaDatabaseHelper.mContext
* leaks com.google.samples.apps.topeka.activity.CategorySelectionActivity instance

And I don't know how to fix it...

**Comment by keyboardsurfer** [comment]
Thanks for this report. Since Topeka is a sample application that showcases material design, fixing this issue this is currently not one of my top priorities. Nonetheless, pull requests are welcome.

**Comment by ardock** [comment]
@Mcflag I recommend you read [this great article by David Smith](https://possiblemobile.com/2013/06/context). Thanks for spotting the issue.

![fix_70](https://cloud.githubusercontent.com/assets/1142360/14404550/c6fe3eba-fe79-11e5-9722-5ac3f47c0a1d.png)
