### ISSUE TITLE
Update Json changes to already Installed Application

### ISSUE THREAD

**Issue by ghost1372** [googlesamples/android-topeka#71]
hi,
If I make any change to <h1> categories.json</h1>   like adding new categories or quizz in my android application. and If I have already installed that on my phone. when I reinstall / update that application on mobile it doesn't update the categories.json changes. (i must unninstal Previous version and install new version To apply the changes)
This problem can be solved in a sqlite database with the following code,but in json i dont know how to fix it.tnx

    private static final int DATABASE_VERSION = 1;
    public DatabaseHandler(Context context) {
    super(context, DATABASE_NAME, null, DATABASE_VERSION);
    }

**Comment by keyboardsurfer** [comment]
Versioning of the database is not implemented in Topeka at the moment.
Feel free to create a pull request with a solid implementation and I'll gladly look into it.

**Comment by ghost1372** [comment]
tnx but i dont know how i can create a pull request?
and i think its better if Topeka Support level manager (for example : https://s.cafebazaar.ir/1/upload/screenshot/com.xalopex.ghalatnameh5.jpg )
and if possible add new method in quiz like this (http://content.chupamobile.com/user-upload2/product-image-screenshot/P5jYwf8prHdrGrTO9QAJSmYM_2_device-2014-12-12-160513.png)

**Comment by keyboardsurfer** [comment]
Please refer to the [GitHub user documentation on pull requests](https://help.github.com/articles/creating-a-pull-request/) for information on this topic. I do not see any benefit for the general developer in implementing an update mechanism for the database at this point in time.
