### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by IgorGanapolsky** [googlesamples/android-topeka#73]
I am unable to do a gradle build on the latest code.  The app's build.gradle fails.  See screenshot:
<img width="1440" alt="screen shot 2016-02-23 at 9 40 15 am" src="https://cloud.githubusercontent.com/assets/201209/13254939/a2f09fe0-da11-11e5-9458-d3dd0a2bce4a.png">

**Comment by keyboardsurfer** [comment]
Can not reproduce with the given information, Android Studio 2.0 Beta 5 and beta5 plugin.
Older versions work flawlessly as well. Please provide more information on the issue.

**Comment by IgorGanapolsky** [comment]
Deleted my fork.  Re-forked and clone.  Imported into Android Studio again, and still getting this error!  Regardless, your project - out of the box - is using `classpath 'com.android.tools.build:gradle:2.0.0-alpha9'`.  How can you posit that it works?

**Comment by keyboardsurfer** [comment]
Because it builds for me as well as others that are using the project.
This is the first itme I'm hearing of that particular issue.
Does `./gradlew clean assembleDebug` work for you?
Also, have you run `android update sdk` recently? If not, please do.

**Comment by IgorGanapolsky** [comment]
Also, your build.gradle was pointing at:
`    gradleVersion = "2.8"`.  I believe this is wrong.

I fixed the issue by deleting and re-adding the `dependencies` closure in build.gradle file.  Now the project builds.
