### ISSUE TITLE
Compiling Topeka in Android Studio

### ISSUE THREAD

**Issue by joshuamugarura** [googlesamples/android-topeka#75]
Hello Developers..Could any one help me with the necessary steps to compile topeka because i get an error that the project doesnot use the graddle build system

**Comment by keyboardsurfer** [comment]
The project is using gradle as build system.
In Android Studio navigate to File > New > Import Project.
Within the resulting dialog navigate to the location of the build.gradle file of the cloned project and click OK.

If that doesn't solve the issue please provide more information.
