### ISSUE TITLE
QuizActivity transition is not smooth

### ISSUE THREAD

**Issue by iPaulPro** [googlesamples/android-topeka#8]
Hoping to get some direction on how to fix issues like this. I often see this type of flickering and misaligned animations when using ActivityOptions to pass views.

![Imgur](http://i.imgur.com/iq9DGG5.gif)

You can add this to `QuizActivity.onCreate()`, but it only stops the status bar/nav bar flickering (and not the misaligned views). It's also a nasty little block of code that shouldn't be necessary everywhere, and I'm hoping there's a better way.

    postponeEnterTransition();

    final View decor = getWindow().getDecorView();
    decor.getViewTreeObserver().addOnPreDrawListener(new ViewTreeObserver.OnPreDrawListener() {
        @Override
        public boolean onPreDraw() {
            decor.getViewTreeObserver().removeOnPreDrawListener(this);
            startPostponedEnterTransition();
            return true;
        }
    });

**Comment by keyboardsurfer** [comment]
Take a look at 9872032bbdbf9fdfc0bd60531bf204317ada5b4c.
Especially [TransitionHelper](https://github.com/googlesamples/android-topeka/blob/master/app/src/main/java/com/google/samples/apps/topeka/helper/TransitionHelper.java) to see how to get rid of the flickering.

**Comment by iPaulPro** [comment]
Thanks Ben, it's definitely better when certain items are selected, but it's still not perfect. 

![topeka-transition-slower](http://i.imgur.com/vWFZsmz.gif)

Sorry to be a nag. Feel free to close this if it's out of the scope of this sample.

**Comment by keyboardsurfer** [comment]
Which device and Android version are you running this on?
I'm unable to reproduce it with 5.1.1.

**Comment by iPaulPro** [comment]
I'm no longer able to replicate. Not sure why I was still seeing that (maybe cached gradle build or something). Thanks.
