### ISSUE TITLE
Model classes implement Parcelable

### ISSUE THREAD

**Issue by samiuelson** [googlesamples/android-topeka#88]
All model classes implement `Parcelable `interface.
In fact "parcelability" of those classes not used anywhere in production code. 
It's used only in tests that are testing if those `Parcelable` classes are being parcelarized correctly. 
Why?

**Comment by keyboardsurfer** [comment]
Thanks a lot for pointing that out. It's one of those things that was left behind from the initial implementation. Only Player actually should be parcelable.

**Comment by keyboardsurfer** [comment]
The kotlin branch no longer has unnecessary `Parcelable` classes. Thanks for reporting!
