### ISSUE TITLE
Answer key and Image 

### ISSUE THREAD

**Issue by aikusuma** [googlesamples/android-topeka#89]
Hi, 
here is a sample question 

>     {
>         "type": "single-select-item",
>         "question": "What U.S. President committed an unpardonable sin by kissing the Queen Mother on the lips?",
>         "options": [
>           "George W. Bush",
>           "Jimmy Carter",
>           "Barack Obama",
>           "Lyndon B. Johnson",
>           "Ronald Reagan"
>         ],
>         "answer": [1]
>       },

What the meaning of **answer": [1]** ?
is 1 stand for George W. Bush? 
or
The answer only 1 ? 
i tried answer George W. Bush  but wrong...

And, 
How to change image logo (Music,Sport,Entertaiment etc) 
Should i change the png or the xml? 
Thank you very much ^_^

**Comment by keyboardsurfer** [comment]
The numbering is zero based.
When looking at the options, the index would be from 0-4, giving each item a unique position.

Changing the images requires both items to change, depending on the Android version you want to run this on.

On another note: This is a sample which I would not recommend for beginning with Android.
In case you want to learn Android in general, [we've got a course at Udacity](https://www.udacity.com/course/android-development-for-beginners--ud837) for that.
