### ISSUE TITLE
Migration to Kotlin.

### ISSUE THREAD

**Issue by erluxman** [googlesamples/android-topeka#96]
Are there any plans about migrating to kotlin? If there are, Would love to contribute migrating.

**Comment by keyboardsurfer** [comment]
Yes there are concrete plans.
I'll update this issue accordingly and let you know about ways to contribute.

**Comment by keyboardsurfer** [comment]
All live now, see the [kotlin](https://github.com/googlesamples/android-topeka/tree/kotlin) branch.

**Comment by yolapop** [comment]
Hi @keyboardsurfer, how long did you take to migrate all code to Kotlin?

**Comment by keyboardsurfer** [comment]
@erluxman I'm happy for any feedback you can give on the kotlin version of topeka.

**Comment by keyboardsurfer** [comment]
`master` now holds the Kotlin implementation. Java implementation moved to `java`
