### ISSUE TITLE
gradle error

### ISSUE THREAD

**Issue by ancymathai** [googlesamples/android-topeka#97]
Error:Unable to find method 'com.android.build.gradle.tasks.factory.AndroidUnitTest.setTestClassesDirs(Lorg/gradle/api/file/FileCollection;)V'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
after cloning project and run in android studio 3.0 canary 4

**Comment by keyboardsurfer** [comment]
Thanks for your report.
Have you followed the instructions provided by the error message?

**Comment by ancymathai** [comment]
solved the error. by replacing gradle 2.3.3
