### ISSUE TITLE
topekaapk/src/main/AndroidManifest.xml. error

### ISSUE THREAD

**Issue by ancymathai** [googlesamples/android-topeka#99]
topekaapk/src/main/AndroidManifest.xml.
<manifest package="com.foobar"
    xmlns:android="http://schemas.android.com/apk/res/android">
</manifest>

after adding this, http://schemas.android.com/apk/res/android shown in red color showing error URI not found ( setting-> languages and frame work->schemas and DTDS)

**Comment by keyboardsurfer** [comment]
This seems line an issue for the [codelab](https://github.com/googlecodelabs/android-topeka/issues) instead of the app. Please file it there.
